# Setup
title:        Today I Learned
tagline:      Another simple 'Today I Learned' website, by a stupid and random guy on the internet.
baseurl:      "/til/"
paginate:     1

# About/contact
author:
  name:       Guillaume Ongenae
  url:        https://g-ongenae.github.io
  email: guillaume.ongenae@gmail.com
  twitter_username: g_ongenae
  github_username:  g-ongenae

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown

exclude:
  - README.md
